# The URL the site will be built for
base_url = "https://edu.dluciv.name"
# —Ç–µ—Ö–Ω–∏—á–µ—Å–∫–∞—è —Å—Å—ã–ª–∫–∞:
# base_url = "https://dluciv.github.io/static-edu.dluciv.name"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Theme
theme = "duckquill"
default_language = "ru"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
emoji_favicon = "üéì"
default_theme = "light"
toc = true

[languages.en]
title = "Dmitry V. Luciv, Education"
description = "Dmitry V. Luciv, Education"
taxonomies = [{ name = "tags", feed = false }]

[languages.ru]
title = "–õ—É—Ü–∏–≤ –î. –í., –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ"
description = "–õ—É—Ü–∏–≤ –î–º–∏—Ç—Ä–∏–π –í–∞–¥–∏–º–æ–≤–∏—á, –æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ"
generate_feeds = false
taxonomies = [{ name = "tags", feed = false }]

[extra.nav]
show_feed = false
show_theme_switcher = true
links = [
#	{ name = "Home", url = "/" },
	{ name = "Links", menu = [
		{ name = "Personal Website", url = "https://dluciv.name/" },
		{ name = "Older Site", url = "https://sites.google.com/view/edu2018-dluciv-name" },
	] },
	{ name = "Disciplines", menu = [
		{ url = "@/courses/internships.md", name = "Internships" },
		{ name = "Algorithms and Data Structures, 2nd Semester", url = "https://sites.google.com/view/edu2018-dluciv-name/Home/algorithms" },
		{ name = "Algorithms and Data Structures, 5th Semester", url = "https://sites.google.com/view/edu2018-dluciv-name/Home/algorythms-s5" },
		{ name = "Hardware Architecture", url =  "https://sites.google.com/view/edu2018-dluciv-name/Home/architecture" },
		{ name = "Modern Software Tools and Technologies", url = "https://sites.google.com/view/edu2018-dluciv-name/Home/modern-tools-techs" },
		{ name = "Distributed Information Processing and NoSQL Databases", url = "https://sites.google.com/view/edu2018-dluciv-name/Home/distrinfproc" }
	] }
]

[extra.footer]
links = [
	{ url = "https://se.math.spbu.ru/", name = "Chair of Software Engineering" },
	{ url = "https://math.spbu.ru/", name = "Faculty of Math" },
	{ url = "https://spbu.ru/", name = "SPbU" }
]

[extra.goatcounter]
user = "edu-dluciv-name"
