# The URL the site will be built for
# base_url = "/"
base_url = "https://edu.dluciv.name"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Theme
theme = "duckquill"
default_language = "ru"


#[languages.ru]
title = "Ð›ÑƒÑ†Ð¸Ð² Ð”Ð¼Ð¸Ñ‚Ñ€Ð¸Ð¹ Ð’Ð°Ð´Ð¸Ð¼Ð¾Ð²Ð¸Ñ‡"
description = "Ð›ÑƒÑ†Ð¸Ð² Ð”Ð¼Ð¸Ñ‚Ñ€Ð¸Ð¹ Ð’Ð°Ð´Ð¸Ð¼Ð¾Ð²Ð¸Ñ‡"
generate_feeds = false
taxonomies = [{ name = "tags", feed = false }]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
[search]
# index_format = "elasticlunr_json"
index_format = "fuse_json"

[languages.en]
title = "Dmitry V. Luciv"
description = "Dmitry V. Luciv"
generate_feeds = false
taxonomies = [{ name = "tags", feed = false }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
# emoji_favicon = "ðŸŽ“"
favicon = "favicon.png"
# default_theme = "system"
toc = true
styles = ["mods.css"]
# Extra scripts
scripts = ["scripts/addmeta.js", "scripts/ext-table.js"]

[extra.nav]
show_feed = false
show_theme_switcher = true
links = [
#	{ name = "Home", url = "/" },
#	{ name = "Links", menu = [
#		{ name = "Personal Website", url = "https://dluciv.name/" },
#		{ name = "Older Site", url = "https://sites.google.com/view/edu2018-dluciv-name" },
#	] },
	{ name = "materials", menu = [
		{ url = "@/internships/masters.md", name = "internships-masters-m1234" },
		{ name = "algds-b2", url = "@/courses/algds-b2.md" },
		{ name = "algds-b5", url = "@/courses/algds-b5.md" },
		{ name = "comp-arch-b24", url =  "@/courses/comparch-b24.md" },
		{ name = "tools-tech-m1", url = "@/courses/modern_tt-m1.md" },
		{ name = "nosql-b7", url = "@/courses/nosql-b7.md" }
	] }
]

[extra.footer]
links = [
	{ url = "https://se.math.spbu.ru/", name = "Chair of Software Engineering" },
	{ url = "https://math.spbu.ru/", name = "Faculty of Math" },
	{ url = "https://spbu.ru/", name = "SPbU" },
	{ url = "https://github.com/dluciv/static-edu.dluciv.name", name = "site_source" },
	{ url = "https://duckquill.daudix.one/", name = "duck" }
]

[extra.goatcounter]
user = "edu-dluciv-name"
